### ISSUE TITLE
Destination not object when scanning iseq

### ISSUE THREAD

**Issue by wks** [mmtk/mmtk-ruby#106]
We observed in the CI https://github.com/mmtk/mmtk-ruby/actions/runs/10933871805/job/30353030059 that a field of an iseq, is pointing to a non-MMTk object.

```
 ERROR: An MMTk GC thread panicked.  This is a bug.
     panicked at src/scanning.rs:42:13:
     Destination is not an MMTk object. Src: 0x200fff6ee58 dst: 0x200fff12718
        0: mmtk_ruby::handle_gc_thread_panic
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/mmtk-ruby/mmtk/src/lib.rs:101:14
        1: mmtk_ruby::set_panic_hook::{{closure}}
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/mmtk-ruby/mmtk/src/lib.rs:130:13
        2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
                  at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/alloc/src/boxed.rs:2029:9
        3: std::panicking::rust_panic_with_hook
                  at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:785:13
        4: std::panicking::begin_panic_handler::{{closure}}
                  at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:659:13
        5: std::sys_common::backtrace::__rust_end_short_backtrace
                  at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/sys_common/backtrace.rs:171:18
        6: rust_begin_unwind
                  at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:647:5
        7: core::panicking::panic_fmt
                  at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/panicking.rs:72:14
        8: <mmtk_ruby::scanning::VMScanning as mmtk::vm::scanning::Scanning<mmtk_ruby::Ruby>>::scan_object_and_trace_edges::{{closure}}
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/mmtk-ruby/mmtk/src/scanning.rs:42:13
        9: mmtk_ruby::abi::ObjectClosure::c_function_registered
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/mmtk-ruby/mmtk/src/abi.rs:217:9
       10: rb_mmtk_call_object_closure
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/build/../mmtk_support.c:516:12
       11: rb_mmtk_mark_and_move
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/build/../mmtk_support.c:590:36
       12: rb_gc_impl_mark_and_move
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/build/../gc/default.c:5226:9
       13: rb_gc_mark_and_move
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/build/../gc.c:2087:5
       14: rb_iseq_mark_and_move
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/build/../iseq.c:351:9
       15: rb_imemo_mark_and_move
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/build/../imemo.c:455:9
       16: rb_gc_update_object_references
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/build/../gc.c:3413:9
       17: rb_mmtk_update_object_references
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/build/../gc/default.c:10721:5
       18: rb_mmtk_scan_object_ruby_style
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/ruby/build/../mmtk_support.c:551:5
       19: <mmtk_ruby::scanning::VMScanning as mmtk::vm::scanning::Scanning<mmtk_ruby::Ruby>>::scan_object_and_trace_edges::{{closure}}
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/mmtk-ruby/mmtk/src/scanning.rs:59:17
       20: mmtk_ruby::abi::ObjectClosure::set_temporarily_and_run_code
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/mmtk-ruby/mmtk/src/abi.rs:201:22
       21: <mmtk_ruby::scanning::VMScanning as mmtk::vm::scanning::Scanning<mmtk_ruby::Ruby>>::scan_object_and_trace_edges
                  at /home/runner/work/mmtk-ruby/mmtk-ruby/git/mmtk-ruby/mmtk/src/scanning.rs:56:9
       22: mmtk::scheduler::gc_work::ScanObjectsWork::do_work_common::{{closure}}
                  at /home/runner/.cargo/git/checkouts/mmtk-core-3306bdeb8eb4322b/73be50d/src/scheduler/gc_work.rs:873:21
```

And the failing test is a btest case:

```
  #344 test_insns.rb:465: 
         r = false
         t = [true, nil]
         q, w, e = r, *t             # here
         w
    #=> "" (expected "true")  concatarray
  FAIL 1/0 tests failed
  make: *** [uncommon.mk:899: yes-btest] Error 1
```

The line `iseq.c:351:9` scans the field `body->location.label`.  Due to the nature of the release build, it may not indicate the exact line, but should be approximate.

We have enabled an aggressive assertion when running CI, i.e. `-DMMTK_WB_ASSERT_VO`, in https://github.com/mmtk/mmtk-ruby/pull/105, even when testing the release build.  But the same error is not observed again after re-running the tests on CI for 5 times.

**Comment by wks** [comment]
We sometimes see errors like this: `Destination is not an MMTk object. Src: 0x20102b0fcd0 dst: 0x20102f78008`, but when debugging in LLDB,

-   `p (char)mmtk_is_mmtk_object(0x0000020102f78008)` prints `1`, which means it is a valid object.
-   `p (char)mmtk_is_reachable(0x0000020102f78008)` prints `1`, which means the object has been reached, maybe by another GC worker thread.
-   `p (char)mmtk_get_forwarded_object(0x0000020102f78008)` prints `0`, which means either the object is pinned, or the field has already been forwarded.  

It is very strange that `mmtk_is_mmtk_object` returns contradicting results in two calls.  It is possible that 0x20102f78008 is allocated during GC (i.e. a copied object in the to-space), and the current GC worker sees its pointer but failed to see the VO bit which is set after the object is allocated.  But this is also unlikely because the `ImmixSpace::trace_object_with_opportunistic_copy` method copies the object, sets the VO bit (atomically using the SeqCst order), and then return the pointer to the object.  So if it is the first time the current GC worker visits a field, it should either

- see a from-space object which must either has the VO bit since the beginning of the GC or never has the VO bit, or
- see a to-space object which has already been forwarded.

That's under the assumption that only one GC worker can be calling `Scanning::scan_object_and_trace_object` on that object at a time.  That's guaranteed by the mark bit (i.e. each object is scanned exactly once).

Since the error happens in `iseq_scan_bits` which scans the `code` (`ISEQ_BODY(iseq)->iseq_encoded`), if the `code` is reachable from two different objects (I don't know if it is the case), this error may happen.  If one GC worker has forwarded the field while another is trying to read from it, and some compiler optimization re-ordered the instructions (which is unlikely because of the semantics of SeqCst), the other GC worker may see the object but not the VO bit.

Full stack trace:

```
ERROR: An MMTk GC thread panicked.  This is a bug.
panicked at src/scanning.rs:42:13:
Destination is not an MMTk object. Src: 0x20102b0fcd0 dst: 0x20102f78008
   0: mmtk_ruby::set_panic_hook::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: mmtk_ruby::abi::ObjectClosure::c_function_registered
   7: rb_mmtk_call_object_closure
             at ./../mmtk_support.c:516:12
   8: rb_mmtk_mark_and_move
             at ./../mmtk_support.c:590:36
   9: iseq_scan_bits
             at ./../iseq.c:225:9
  10: rb_iseq_mark_and_move_each_value
             at ./../iseq.c:288:13
  11: rb_iseq_mark_and_move
             at ./../iseq.c:346:9
  12: <mmtk::scheduler::gc_work::PlanScanObjects<E,P> as mmtk::scheduler::work::GCWork<<E as mmtk::scheduler::gc_work::ProcessEdgesWork>::VM>>::do_work
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: core::ops::function::FnOnce::call_once{{vtable.shim}}
  15: std::sys::pal::unix::thread::Thread::new::thread_start
  16: <unknown>
  17: <unknown>
```

**Comment by wks** [comment]
This is also reproducible when running the following test case in `bootstraptest/test_io.rb`.

```ruby
/freebsd/ =~ RUBY_PLATFORM or
10.times do
  assert_normal_exit %q{
    at_exit { p :foo }

    megacontent = "abc" * 12345678
    #File.write("megasrc", megacontent)

    t0 = Thread.main
    Thread.new { sleep 0.001 until t0.stop?; Process.kill(:INT, $$) }

    r1, w1 = IO.pipe
    r2, w2 = IO.pipe
    t1 = Thread.new { w1 << megacontent; w1.close }
    t2 = Thread.new { r2.read; r2.close }
    IO.copy_stream(r1, w2) rescue nil
    w2.close
    r1.close
    t1.join
    t2.join
  }, 'megacontent-copy_stream', ["INT"], :timeout => 10 or break
end
```

And it is even more reproducible if we don't send the SIGINT signal.  We can even save that test case into a `.rb` file and run it repeatedly using `miniruby`.  It can be reproduced by running it repeatedly about 1-20 times.

When it happens, it also reports the destination is not an MMTk object, for example,

```
Destination is not an MMTk object. Src: 0x200ffee14d8 dst: 0x201002f8008
```

But when debugging in GDB,

```
(gdb) p (bool)mmtk_is_mmtk_object(0x201002f8008ULL)
$1 = true
(gdb) p (bool)mmtk_is_reachable(0x201002f8008ULL)
$2 = true
(gdb) p (uintptr_t)mmtk_get_forwarded_object(0x201002f8008ULL)
$3 = 0
```

This is consistent with https://github.com/mmtk/mmtk-ruby/issues/106#issuecomment-2376335002

And this is not reproducible if I set `MMTK_THREADS=1`, i.e. using only one GC worker thread.  It indicates that there is some race condition between the query of VO bit and the setting of VO bit.

And I can't reproduce it using `rr` after running it 1000 times.  It's likely that the presence of RR altered the behavior of the multi-threaded program.

**Comment by wks** [comment]
It is caused by a bug in mmtk-core. See https://github.com/mmtk/mmtk-core/issues/1213

The reason why it always manifests in `iseq` is that `iseq` is one of the few types that use `rb_gc_mark_and_move`.  In the current MMTk-Ruby binding, `rb_mmtk_scan_object_ruby_style` calls both `gc_mark_children` and `rb_gc_update_object_references`.  When scanning an `iseq`, both will call `rb_iseq_mark_and_move`, but the former has `reference_updating` being false, and the latter has `reference_updating` being true.  Regardless of the value of `reference_updating`, `rb_gc_mark_and_move` will be forwarded to `trace_object` and will update the field.  If a field is being updated the second time, it will load from the field and see a reference to the to-space object.  Because of the bug described in https://github.com/mmtk/mmtk-core/issues/1213, the assertion will fail because the VO bit is not set on the to-space copy.
