### ISSUE TITLE
hash table stuck in a loop finding secondary hash

### ISSUE THREAD

**Issue by wks** [mmtk/mmtk-ruby#44]
When running a very simple microbenchmark, ruby got stuck after the first GC.  The stack trace is:

```
#0  secondary_hash (perturb=<synthetic pointer>, tab=<optimized out>, ind=<optimized out>) at ../st.c:818
#1  find_table_bin_ind (tab=tab@entry=0x555555db8af0, hash_value=hash_value@entry=240487933751235266, key=<optimized out>) at ../st.c:933
#2  0x0000555555711baf in rb_st_update (tab=tab@entry=0x555555db8af0, key=<optimized out>, key@entry=2203317796872, func=func@entry=0x55555571bb90 <fstr_update_callback>, arg=arg@entry=140737488346928)
    at ../st.c:1457
#3  0x000055555572d27e in register_fstring (copy=false, str=2203317796872) at ../string.c:613
#4  rb_fstring (str=str@entry=2203317796872) at ../string.c:592
#5  0x0000555555741e70 in register_static_symid_str (str=2203317796872, id=25761) at ../symbol.c:559
#6  intern_str (str=2203317796872, mutable=mutable@entry=1) at ../symbol.c:782
#7  0x00005555557424f1 in rb_intern3 (enc=0x555555e31d80, len=9, name=0x555555995721 "load_iseq") at ../symbol.c:731
#8  rb_intern3 (enc=0x555555e31d80, len=9, name=0x555555995721 "load_iseq") at ../symbol.c:722
#9  rb_intern2 (len=9, name=0x555555995721 "load_iseq") at ../symbol.c:788
#10 rb_intern (name=0x555555995721 "load_iseq") at ../symbol.c:795
#11 0x00005555558f2f9c in rb_undef_method (klass=2203317859512, name=<optimized out>) at ../class.c:2156
#12 0x00005555555ea16b in rb_call_inits () at ../inits.c:65
#13 0x00005555555a8400 in ruby_setup () at ../eval.c:89
#14 0x00005555555a84a9 in ruby_init () at ../eval.c:101
#15 0x00005555555a300a in rb_main (argv=0x7fffffffe268, argc=3) at ../main.c:45
#16 main (argc=<optimized out>, argv=<optimized out>) at ../main.c:65
```

The first GC happened when `rb_intern3` allocated a new string object.  During the GC, the MMTk binding updated the frozen strings table.  After that, when looking up an element in the table, it falls into an infinite loop, finding the next secondary hash.

I think there is a bug in the code that updates the hash table.  Somehow it failed to put a stopping sign in the table, causing the searching algorithm to keep thinking the value is in the next bin.

This may also explain why the CI sometimes hang and gets killed after several hours.

**Comment by wks** [comment]
This could be caused by the same bug as https://github.com/mmtk/ruby/issues/69.  It also happens when registering fsting and is related to the hash.  If we erroneously deleted the wrong entry, it could cause the hash table to search for the element forever.  I am closing this issue.
